
def intro():
    print("Hello! This is a logic parser!")
    print("PLEASE READ THE INPUT RULES CAREFULLY")
    print("")
    print("")
    print("VARIABLES")
    print("- only use letters of the alphabet for variable names")
    print("- do NOT use numbers for variable names.")
    print("- variable names should be 1 character long")
    print("- you may input '0' or '1' for False or True respectively")
    print("")
    print("")
    print("VALID CONNECTIVES")
    print("Here are the symbols you should use:")
    print("")
    print("for disjunction, type '|' or 'or',")
    print("for conjunction, type '&' or 'and',")
    print("for negation, type '~' or '!' or 'not',")
    print("for exclusive or, type '^' or 'xor',")
    print("for implication, type '->' or 'implies',")
    print("for biimplication, type '<->' or 'if-and-only-if',")
    print("for NAND, type '!&' or 'nand',")
    print("for NOR, type 'nor'.")
    print("")
    print("")
    print("NOTES")
    print("- implication will associate to the right.")
    print("")
    print("You don't have to be perfect with your inputs, because")
    print("Spaces will be removed and reformatted to fit the parser.")
    print("However, if you input a formula using words (e.g., A and B)")
    print("Please use spaces to set off your connectives.")
    print("")
    INPUT = input("Paste in logical expression.")
    return INPUT